#pragma once

#include "shared/keyvalues.h"
#include "core/math/color.h"
#include "inputsystem/ButtonCode.h"

extern vgui::Panel* (*vgui_Panel_FindChildByName)(vgui::Panel* thisptr, const char* childName, bool recurseDown);

// I make no guarantees that this vtable is even remotely correct, I did this like a year ago
// most of the funcs not labelled are some random things that aren't virtual in portal 2 so it's a bit of a chore if anyone wants to give it a crack you got this

struct DmxElementUnpackStructure_t;
class CDmxElement;

namespace vgui
{

class PanelMessageMap;
class PanelAnimationMap;
class PanelKeyBindingMap;
class IBorder;
class BuildGroup;
class IScheme;
struct KeyBindingContextHandle_t;

class Panel
{
public:
	virtual __int64 MysteryOffsetGetter();
	virtual __int64 nullsub_227();
	virtual __int64 Unk2();
	virtual __int64 sub_76B7E0();
	virtual __int64 sub_76ADE0();
	virtual __int64 sub_76DDB0();
	virtual __int64 sub_765BE0();
	virtual __int64 sub_75BE80();
	virtual __int64 sub_75B680();
	virtual __int64 nullsub_83();
	virtual __int64 sub_76A580();
	virtual __int64 nullsub_220();
	virtual __int64 nullsub_1275();
	virtual __int64 sub_76DF20();
	virtual __int64 sub_76DDF0();
	virtual __int64 sub_76DEA0();
	virtual __int64 sub_76DE20();
	virtual __int64 OnMessage();
	virtual __int64 nullsub_16();
	virtual __int64 sub_75D7D0();
	virtual __int64 sub_764C10();
	virtual __int64 GetSomeUtlString();
	virtual __int64 GetElementNameMaybe();
	virtual __int64 sub_75D030();
	virtual __int64 sub_9E120();
	virtual __int64 sub_7648B0();
	virtual __int64 sub_7583B0();
	virtual Panel ReturnSelfIfNoA2(__int64 a2);
	virtual Panel* GetSelf();
	virtual const char* GetControlsModuleName();
	virtual __int64 nullsub_90();
	virtual PanelMessageMap* GetMessageMap();
	virtual PanelAnimationMap* GetAnimMap();
	virtual PanelKeyBindingMap* GetKBMap();
	virtual DmxElementUnpackStructure_t* GetUnpackStructure();
	virtual ~Panel();
	virtual void SetVisible(bool state);
	virtual bool IsVisible();
	virtual bool IsFullyVisible();
	virtual void PostMessage(Panel* target, KeyValues* message, float delay);
	virtual void PostMessage(unsigned int target, KeyValues* message, float delaySeconds);
	virtual __int64 nullsub_1280();
	virtual Panel* GetParent();
	virtual int GetVParent();
	virtual void SetParent(unsigned int newParent);
	virtual void SetParent(Panel* newParent);
	virtual bool HasParent(unsigned int potentialParent);
	virtual __int64 nullsub_93();
	virtual void SetAutoDelete(bool state);
	virtual void AddActionSignalTarget(unsigned int messageTarget);
	virtual void AddActionSignalTarget(Panel* messageTarget);
	virtual void RemoveActionSignalTarget(Panel*);
	virtual void PostActionSignal(KeyValues* message);
	virtual __int64 RequestInfoFromChild(const char* childName, KeyValues* data);
	virtual void PostMessageToChild(const char* childName, KeyValues* message);
	virtual bool SetInfo(KeyValues* inputData);
	virtual void SetSilentMode(bool bSilent);
	virtual void InstallMouseHandler(Panel* pHandler);
	virtual void SetEnabled(bool state);
	virtual bool IsEnabled();
	virtual bool IsPopup();
	virtual void MoveToFront();
	virtual void SetBgColor(Color color);
	virtual void SetFgColor(Color color);
	virtual Color* GetBgColor();
	virtual Color GetFgColor();
	virtual bool HasFocus();
	virtual __int64 Unk1();
	virtual __int64 Unk3();
	virtual void SetTabPosition(int position);
	virtual void SetBorder(IBorder* border);
	virtual IBorder* GetBorder();
	virtual void SetPaintBorderEnabled(bool state);
	virtual void SetPaintBackgroundEnabled(bool state);
	virtual void SetPaintEnabled(bool state);
	virtual void SetPostChildPaintEnabled(bool state);
	virtual void SetPaintBackgroundType(int type);
	virtual void GetPaintSize(int* wide, int* tall);
	virtual void SetBuildGroup(BuildGroup *buildGroup);
	virtual bool IsBuildGroupEnabled();
	virtual bool IsCursorNone();
	virtual bool IsCursorOver();
	virtual void MarkForDeletion();
	virtual bool IsLayoutInvalid();
	virtual __int64 nullsub_15();
	virtual bool IsOpaque();
	virtual void SetScheme(unsigned long scheme);
	virtual void SetScheme(const char* tag);
	virtual Color* GetSchemeColor(const char* keyName, Color defaultColor, IScheme* pScheme);
	virtual Color* GetSchemeColor(const char* keyName, IScheme* pScheme);
	virtual void ApplySchemeSettings(IScheme* pScheme);
	virtual __int64 sub_756600();
	virtual void OnUnserialized(CDmxElement* pElement);
	virtual void GetSettings(KeyValues* outResourceData);
	virtual const char* GetDescription();
	virtual __int64 nullsub_1272();
	virtual __int64 nullsub_1274();
	virtual __int64 nullsub_14();
	virtual void OnCommand(const char* command);
	virtual void OnMouseCaptureLost();
	virtual void OnKillFocus_0();
	virtual void OnKillFocus();
	virtual void Release();
	virtual void OnThink();
	virtual void OnCursorMoved(int x, int y);
	virtual __int64 nullsub_85();
	virtual __int64 nullsub_86();
	virtual __int64 nullsub_87();
	virtual __int64 nullsub_102();
	virtual __int64 nullsub_88();
	virtual void OnMouseWheeled(int delta);
	virtual void SetTriplePressAllowed(bool state);
	virtual bool IsTriplePressAllowed();
	virtual __int64 nullsub_89();
	virtual void SetKeyBindingsContext(KeyBindingContextHandle_t handle);
	virtual KeyBindingContextHandle_t GetKeyBindingsContext();
	virtual bool IsValidKeyBindingsContext();
	virtual bool IsKeyRebound(ButtonCode_t code, int modifiers);
	virtual __int64 ret0_0();
	virtual __int64 AddKeyBinding();
	virtual __int64 nullsub_1273();
	virtual __int64 GetKeyBindingsFile();
	virtual __int64 GetKeyBindingsFilePathID();
	virtual __int64 OnKeyCodePressed();
	virtual __int64 OnKeyCodeTyped();
	virtual __int64 OnKeyTyped();
	virtual __int64 OnKeyCodeReleased();
	virtual __int64 OnKeyFocusTicked();
	virtual __int64 OnMouseFocusTicked();
	virtual __int64 PaintBackground();
	virtual __int64 nullsub_91();
	virtual __int64 PaintBorder();
	virtual __int64 PaintBuildOverlay();
	virtual __int64 nullsub_92();
	virtual __int64 PerformLayout();
	virtual __int64 GetPanelMap();
	virtual __int64 SetProportional();
	virtual __int64 SetMouseInputEnabled();
	virtual __int64 SetKeyboardInputEnabled();
	virtual __int64 IsMouseInputEnabled();
	virtual __int64 IsKeyboardInputEnabled();
	virtual __int64 DrawTexturedBox();
	virtual __int64 DrawBox();
	virtual __int64 DrawBoxFade();
	virtual __int64 DrawHollowBox();
	virtual __int64 sub_759180();
	virtual __int64 SetDragEnabled();
	virtual __int64 IsDragEnabled();
	virtual __int64 SetShowDragHelper();
	virtual __int64 nullsub_1276();
	virtual __int64 SetBlockDragChaining();
	virtual __int64 IsBlockingDragChaining();
	virtual __int64 GetDragStartTolerance();
	virtual __int64 SetDragStartTolerance();
	virtual __int64 SetDropEnabled();
	virtual __int64 IsDropEnabled();
	virtual __int64 nullsub_13();
	virtual __int64 nullsub_1278();
	virtual __int64 nullsub_1277();
	virtual __int64 GetUnlocalizedTextSymbol();
	virtual __int64 nullsub_1279();
	virtual __int64 nullsub_84();
	virtual __int64 nullsub_12();
	virtual __int64 OnDraggablePanelPaint();
	virtual __int64 OnDroppablePanelPaint();
	virtual __int64 nullsub_1283();
	virtual __int64 nullsub_1284();
	virtual __int64 nullsub_1285();
	virtual __int64 GetDropTarget();
	virtual __int64 GetDragPanel();
	virtual __int64 IsBeingDragged();
	virtual __int64 GetDropCursor();
	virtual __int64 GetDragFailCursor();
	virtual __int64 CanStartDragging();
	virtual __int64 FillRectSkippingPanel();
	virtual __int64 GetPaintBackgroundType();
	virtual __int64 GetCornerTextureSize();
	virtual __int64 SetSkipChildDuringPainting();
	virtual __int64 NavigateUp();
	virtual __int64 NavigateDown();
	virtual __int64 NavigateLeft();
	virtual __int64 NavigateRight();
	virtual __int64 NavigateTo();
	virtual __int64 NavigateFrom();
	virtual __int64 NavigateToChild();
	virtual __int64 nullsub_1282();
	virtual __int64 nullsub_1281();
	virtual __int64 nullsub_4();
	virtual __int64 nullsub_11();
	virtual __int64 nullsub_2();
	virtual __int64 nullsub_1();
	virtual __int64 nullsub_0();
	virtual __int64 nullsub_();
	virtual __int64 OnRequestFocus();
	virtual __int64 nullsub_10();
	virtual __int64 nullsub_9();
	virtual __int64 nullsub_8();
	virtual __int64 nullsub_7();
	virtual __int64 sub_9E140();
	virtual __int64 nullsub_5();
	virtual __int64 OnStartDragging();
	virtual __int64 OnContinueDragging();
	virtual __int64 OnFinishDragging();
	virtual __int64 DragDropStartDragging();
	virtual __int64 GetDragData();
	virtual __int64 CreateDragData();
	virtual __int64 sub_76A250();
	virtual __int64 OnScreenSizeChanged();
	virtual __int64 InternalCursorMoved();
	virtual __int64 InternalCursorEntered();
	virtual __int64 InternalCursorExited();
	virtual __int64 InternalMousePressed();
	virtual __int64 InternalMouseDoublePressed();
	virtual __int64 InternalMouseTriplePressed();
	virtual __int64 InternalMouseReleased();
	virtual __int64 InternalMouseWheeled();
	virtual __int64 InternalKeyCodePressed();
	virtual __int64 InternalKeyCodeTyped();
	virtual __int64 InternalKeyTyped();
	virtual __int64 InternalKeyCodeReleased();
	virtual __int64 InternalKeyFocusTicked();
	virtual __int64 InternalMouseFocusTicked();
	virtual __int64 RereadAllItems();
	virtual __int64 InternalMove();
	virtual __int64 GetSizerMinimumSize();
	virtual __int64 GetSizerClientArea();
	virtual __int64 RetSomeInt32Const();
	virtual __int64 nullsub_216();
	virtual __int64 nullsub_228();
	virtual __int64 nullsub_17();

	Panel* FindChildByName(const char* childName, bool recurseDown) { return vgui_Panel_FindChildByName(this, childName, recurseDown); }
};

}
